---
name: Deploy Cloudflare Worker

on:

  pull_request_target:
    branches:
      - master
    types:
      - closed

jobs:

  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Configure Cloudflare API Token
        run: npm run configure -- secret.gh_token ${{ secrets.GH_TOKEN }}

      - name: Deploy Cloudflare Worker
        run: npm run deploy
